### PR TITLE
Added WSL instructions

### PR DESCRIPTION
**Pull request by rodelgc**
This PR adds setup instructions in the E2E README doc for setting up the local development environment using WSL.
The changes in this PR will be the same as the changes in my [similar PR in WC Core](https://github.com/woocommerce/woocommerce/pull/31082), which is currently being reviewed.

### CODE REVIEW

**Comment by rodelgc** [comment]
I submitted a similar [PR in WooCommerce Core](https://github.com/woocommerce/woocommerce/pull/31082)

**Comment by rodelgc** [comment]
Updating the issue description to mention that this PR will contain the same changes as [my similar PR in WooCommerce Core](https://github.com/woocommerce/woocommerce/pull/31082). Therefore, I'll wait for the review on that PR to be completed first before reflecting the changes there to this PR.

**Comment by rodelgc** [comment]
Done reflecting the final changes from the Core PR. Ready for another round of review!

**Review by zhongruige — APPROVED** [review]
These look good to me--thanks for adding these in @rodelgc!

**Pull request merged**
